# Generated by Django 4.0.5 on 2022-07-03 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='photo',
            options={'ordering': ('-create',)},
        ),
    ]
